services:
  app:
    container_name: app
    image: "mcr.microsoft.com/devcontainers/python:1-3.10-bookworm"
    platform: linux/amd64
    tty: true
    volumes:
      - type: bind
        source: ../
        target: /workspaces/mongodb-functions
    environment:
      # DevContainer内でBicep拡張機能を動かすため設定
      DOTNET_EnableWriteXorExecute: 0
    depends_on:
      - mongo
    network_mode: service:azurite
  azurite:
    container_name: azurite
    image: mcr.microsoft.com/azure-storage/azurite
    restart: unless-stopped
  mongo:
    container_name: mongo
    restart: always
    image: mongo:4.2
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
